swagger: "2.0"
info:
  title: souvenir-microservice
  description: souvenir-microservice
  version: 1.0.0

paths:
  /swap:
    post:
      operationId: app.flask.routes.Swap.swap
      summary: Endpoint to post portrait and source image.
      consumes:
        - application/json
      produces:
        - text/plain
      responses:
        201:
          description: OK
  /detect_faces:
    post:
      operationId: app.flask.routes.Swap.detect_faces
      summary: Endpoint to detect amount of faces.
      consumes:
        - application/json
      produces:
        - application/json
      responses:
        201:
          description: OK
          schema:
            type: object
            properties:
              number_of_faces:
                type: number
                description: number of faces detected

